# Generated by Django 5.1.3 on 2024-11-08 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UDVogueApp', '0002_remove_editorial_revistas_publicadas_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='producto',
            new_name='revista',
        ),
    ]
