# Generated by Django 5.1.3 on 2024-11-09 21:07

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UDVogueApp', '0003_rename_producto_producto_revista'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editorial',
            name='contacto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='nombre_producto',
        ),
        migrations.RemoveField(
            model_name='revista',
            name='fecha_publi',
        ),
        migrations.RemoveField(
            model_name='revista',
            name='numero_edicion',
        ),
        migrations.AddField(
            model_name='editorial',
            name='cif',
            field=models.CharField(default='000000000000', max_length=12),
        ),
        migrations.AddField(
            model_name='producto',
            name='color',
            field=models.CharField(default='Sin color', max_length=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='nombreProducto',
            field=models.CharField(default='Producto Genérico', max_length=60),
        ),
        migrations.AddField(
            model_name='producto',
            name='talla',
            field=models.CharField(default='M', max_length=3),
        ),
        migrations.AddField(
            model_name='revista',
            name='fechaPublicacion',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='revista',
            name='numeroEdicion',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='nombre',
            field=models.CharField(default='Editorial Desconocida', max_length=80),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='producto',
            name='revista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='UDVogueApp.revista'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='revista',
            name='editorial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revistas', to='UDVogueApp.editorial'),
        ),
        migrations.AlterField(
            model_name='revista',
            name='titulo',
            field=models.CharField(default='Título Desconocido', max_length=50),
        ),
    ]
